### PR TITLE
Compiling and running in v0.15.1284

### PR DESCRIPTION
**Pull request by etinquis**
Anecdotally It seems to run alright, but it could certainly use more testing.

I've just removed the things I encountered related to #173.  It seemed like a reasonable first-pass just to get it up and running.

### CODE REVIEW

**Comment by etinquis** [comment]
Known issue: The minimap appears behind the learning helper.

**Comment by Fasle** [comment]
Damn you beat me :) 

I had it compile, and updated the changed BingingDrug thing by writing a new pleasuredrug method. But I did not have time to figure out why the main menu UI was missing ... buttons are called controls now ... ok Einstein. 

Thanks for the effort, I'll test it over the weekend. I would then start on Combat Realism -- any first thoughts on compatibility issues based on your understanding of changes in a15?

**Comment by etinquis** [comment]
Not sure re: compatibility, I'm a newbie to the project and to Rimworld modding in general so all I did was work through errors as they came up.  I haven't done any sort of regression analysis, I only tried to change as little as possible to get it functional.  With the exception of the removal of the BingingAlcohol stuff, the changes  I've made to this point are fairly superficial.

It could still be that there's code from core missing from some of the injected methods.  The only one I caught and fixed was https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/pull/175/files#diff-987a61a01f59b0381257acae2b3ce6baR100, because it ended up being a compilation error.

EDIT:  It wasn't a compilation error, I was seeing the exception in the default case.

**Comment by TheKrush** [comment]
I think as you look at issue https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/issues/173 they main game just replace Alcohol with a more generic Drug name, so I'd think CCL wants that as well. I honestly don't know what they were/are using those detours for though.

**Comment by Fasle** [comment]
Ok so I got CCL running with Combat Realism last weekend, and tested it for a short game on a15. Everything seemed to work well. This week I am on a business trip and have 0 time to do anything, but after 9/20 I'll start a fork with my version of the pleasuredrug function for you to check. I'll also upload CR. 

What I have not done for CCL is to look how to improve the handling of the new drug types and expand upon vanilla. I am also not yet comfortable enough with Rimworld to tell if all the features are still needed.

**Comment by ForsakenShell** [comment]
Sorry for the long response time, these last few weeks have been murder for me.

I have the library almost completely updated but I still have a few issues to work out.  I'm hoping that it'll be in a playable state in the next week or two but that is dependant on my available time to to work on it.

**Comment by etinquis** [comment]
@ForsakenShell Do you have anything that you can push?  Judging by the demand in various forums, I doubt you'd have a hard time unloading some of the testing burden on some willing candidates.

And there are at least a couple people willing to hack on the code, as well.

**Comment by ForsakenShell** [comment]
Pushing anything now would be premature.  I am in the process of refactoring certain code sections and having an "A14 version" running in A15 wouldn't provide any useful results from testing.  This is pretty typical of the alpha update process and people will unfortunately just have to be patient with me while I get the major refactors done.

**Pull request closed without merging**
