### PR TITLE
Better help view

### PR DESCRIPTION
**Pull request by Karel-Kroeze**
Overall tweaks to the display of the help tab, smaller margins, better way of indenting.
First pass at filtering (ran into a bit of a wall since I can't very well go and alter the category defs, but it's better than nothing, right?)
Fully tested and working. 
image

Note: haven't updated DLL, frankly because I couldn't be arsed to figure the post build script stuff out.

### CODE REVIEW

**Comment by Karel-Kroeze** [comment]
I realised I can probably achieve filtering down to individual helpdefs with some extension methods, will look into that tonight.

**Comment by Karel-Kroeze** [comment]
done and done.

**Comment by ForsakenShell** [comment]
The PostBuild.txt file just needs to be renamed/copied as PostBuild.bat.

If you want to copy the dll to any place other than the mod directories (such as your RimWorld install location), you just need to add the copy command to the end of the file.

As to the PR, looks great, the help menu needed some TLC

**Comment by ForsakenShell** [comment]
Sorry about the revert, I will merge but it needs to be on the development branch, only when a new release is ready do I merge from that branch to the master.

**Pull request merged**
