### PR TITLE
French translation (25 Juillet 2016)

### PR DESCRIPTION
**Pull request by MossieuLeblanc**
I translated every Keyed and tried to translate 2 Defs folders, without sucess

### CODE REVIEW

**Comment by ForsakenShell** [comment]
All pull requests should be to the development branch, we only update master from our development branch when we do a release.

**Comment by MossieuLeblanc** [comment]
Sorry about that, 
i'm learning :)

**Comment by ForsakenShell** [comment]
No worries.  A year ago I completely broke our repo because I was still learning git.  To be honest I still don't really know git, I just use gitgui and fake my way throught it.  ;)

**Comment by kaptain-kavern** [comment]
n00bz ... i once format a local hard disk while thinking it was my webserver (with a `sudo` of course, otherwise no fun ^^)

**Pull request closed without merging**
